#!/usr/bin/env bash
#
# Task-head depth sweep for the hyperedge prediction task.
# Trains one model per task-head depth (number of transformer-encoder layers)
# for num_layers in {1, 2, 3, 4}.
#
# Each run is fully isolated -- its own checkpoint dir, metadata dir, and W&B run
# name -- so the runs never clobber one another's outputs.
#
# It works by writing a small per-run *override* config that points at the base
# config via the `default_config:` key (see digitalcell/conf/utils.py:load_config,
# which deep-merges the override onto the base). Only model.num_layers and the
# per-run output paths/names differ between runs.
#
# ----------------------------------------------------------------------------
# THIS LAUNCHES REAL TRAINING. It is provided set-up-but-not-run on purpose.
# Before running:
#   1. Fill in the real paths in the base config (backbone_path, data_dir,
#      embeddings_path, logger.save_dir/project, etc.). The shipped config has
#      'path/to/...' placeholders.
#   2. Make sure `digitalcell` is importable (e.g. `python -m pip install .`).
# ----------------------------------------------------------------------------
#
# Multi-GPU:
#   * SINGLE-NODE multi-GPU works out of the box -- the trainer block sets
#     strategy=ddp_find_unused_parameters_true and devices='auto' (all visible
#     GPUs), and Lightning spawns one process per GPU when you run the script.
#     Each sweep run uses the whole node and runs to completion before the next.
#   * MULTI-NODE: set `num_nodes` in the base config's trainer block and launch
#     this script on every node under your cluster's launcher (e.g. torchrun).
#     This cluster is NOT SLURM-managed, so do not rely on Lightning's SLURM
#     auto-detection -- use the launcher your cluster provides.
#   * To instead run the four depths CONCURRENTLY, one per GPU, set
#     DEVICES_PER_RUN=1 and pin each run to a GPU via CUDA_VISIBLE_DEVICES
#     (see the commented block at the bottom).
#
# Usage:
#   bash run_num_layers_sweep.sh
#
# Environment overrides (all optional):
#   BASE_CONFIG   Path to the base config         (default: ./conf/hyperedge_config.yaml)
#   OUTPUT_ROOT   Root dir for all sweep outputs  (default: <repo>/sweeps/hyperedge_num_layers)
#   LAYERS        Space-separated layer counts    (default: "1 2 3 4")
#   PYTHON        Python interpreter              (default: python)

set -euo pipefail

# --- locate this script and the repo root (script lives in digitalcell/tasks/hyperedge/) ---
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"

# --- knobs ---
BASE_CONFIG="${BASE_CONFIG:-$SCRIPT_DIR/conf/hyperedge_config.yaml}"
OUTPUT_ROOT="${OUTPUT_ROOT:-/data/arch3d/hyperedge/sweeps/hyperedge_num_layers}"
LAYERS="${LAYERS:-1 2 3 4}"
PYTHON="${PYTHON:-python}"

TRAIN_SCRIPT="$SCRIPT_DIR/hyperedge.py"
GEN_CONFIG_DIR="$OUTPUT_ROOT/configs"

if [[ ! -f "$BASE_CONFIG" ]]; then
    echo "ERROR: base config not found: $BASE_CONFIG" >&2
    exit 1
fi

mkdir -p "$GEN_CONFIG_DIR"

echo "Sweep over task-head depth (num_layers): $LAYERS"
echo "  base config : $BASE_CONFIG"
echo "  output root : $OUTPUT_ROOT"
echo

# Run from the repo root so the 'digitalcell.*' absolute imports resolve even if
# the package was not pip-installed.
cd "$REPO_ROOT"

for N in $LAYERS; do
    RUN_DIR="$OUTPUT_ROOT/num_layers_${N}"
    OVERRIDE_CONFIG="$GEN_CONFIG_DIR/num_layers_${N}.yaml"

    # Generate the per-run override config. Absolute default_config path so it
    # resolves regardless of the working directory.
    cat > "$OVERRIDE_CONFIG" <<EOF
# Auto-generated by run_num_layers_sweep.sh -- task-head depth sweep run.
# Inherits everything from the base config and overrides only what differs.
default_config: '$BASE_CONFIG'

model:
  num_layers: $N

trainer:
  default_root_dir: '$RUN_DIR/checkpoints'

datamodule:
  metadata_dir: '$RUN_DIR/metadata'

logger:
  name: 'hyperedge_num_layers_${N}'
EOF

    echo "=== num_layers=$N ==="
    echo "  config: $OVERRIDE_CONFIG"
    echo "  output: $RUN_DIR"
    "$PYTHON" "$TRAIN_SCRIPT" --config "$OVERRIDE_CONFIG"
    echo
done

echo "Sweep complete. Outputs under: $OUTPUT_ROOT"

# ----------------------------------------------------------------------------
# Concurrent variant (one depth per GPU, all four at once on a 4-GPU node):
#
#   GPU=0
#   for N in 1 2 3 4; do
#       RUN_DIR="$OUTPUT_ROOT/num_layers_${N}"
#       OVERRIDE_CONFIG="$GEN_CONFIG_DIR/num_layers_${N}.yaml"
#       # (generate $OVERRIDE_CONFIG as above, but also set `devices: 1` in its
#       #  trainer block so each run claims a single GPU)
#       CUDA_VISIBLE_DEVICES=$GPU "$PYTHON" "$TRAIN_SCRIPT" --config "$OVERRIDE_CONFIG" &
#       GPU=$((GPU + 1))
#   done
#   wait
# ----------------------------------------------------------------------------
