ckpt_path: null # str. Path to a checkpoint to load the model from. Set to null to train from scratch.

# Parameters to initialize the foundation model
# config class `HiCT_Config` can be found at /digitalcell/model/hict.py
model:
 
  d_model: 1024 # int. Model dimension.
  num_heads: 16 # int. Number of encoder attention heads
  dim_feedforward: 4096 # int. Feedforward dimension of the ffn in the encoder.
  dropout: 0.1 # float. Dropout rate in the encoder
  activation: 'relu' # str. Activation function in the transformer encoder. Choices are ['relu', 'gelu', 'leaky_relu', 'tanh']
  num_layers: 24 # int. Number of transformer blocks in the encoder.
  prepend_cls: false # bool. Prepend the cls token to the input sequence.

  use_gaussian_fourier_features: false # bool. Use Gaussian Fourier features for the positional encoding
  fourier_feature_scale: 1000 # int. Standard deviation for Gaussian Fourier features. Only needed if use_gaussian_fourier_features is true. Must be positive

  # Optimization parameters
  optim:
      scheduler: 'cosine_annealing_with_restarts' # str. Learning rate scheduler ['inverse_sqrt', 'cosine_annealing', 'cosine_annealing_with_restarts']
      warmup_steps: 500 # int. Number of warmup steps to use during training.
      constant_steps: 3000 # int. Number of constant steps to use during training.
      T_max: 5000 # int. Maximum number of steps to use for the cosine annealing scheduler.
      lr: 1e-5 # float. Initial learning rate for optimizer.
      min_lr: 1e-6 # float. Minimum learning rate for optimizer

# Parameters to initialize the datamodule
# datamodule definition can be found at /digitalcell/data/hic/datamodule.py
dataset:
  max_len: 1024 # int. Encoder input sequence length
  num_masked: 200 # int
  num_unchanged: 824 # int
  loci_sampler_vals: 
    - 1
    - 2
    - 5
    - 10
    - 20
    - 50 
    - 100
    - 200
  loci_sampler_probs: null # Iterable[float] | null. Loci sampler probabilities. Uniform by default
  fixed_grid: false # bool
  max_workers: 1 # int
  chroms:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
    - 11
    - 12
    - 13
    - 14
    - 15
    - 16
    - 17
    - 18
    - 19
    - 20
    - 21
    - 22
  
datamodule:
  data_dir: 
   - /path/to/mcool/files/ # Path. Path to the directory containing the .mcool files. Can include multiple paths.
  data_split: # Iterable[float]. Train, validation, and test split.
    - 0.8 # train
    - 0.2 # val
    - 0. # test
  batch_size: 2 # int. Batch size.
  num_workers: 0 # int. Number of workers.
  prefetch_factor: null # int.
  seed: 42 # int. Random seed.
  metadata_dir: '/path/to/metadata/directory' # Path. Directory to where the train and validation file names will be written.
  drop_last: true
  max_files: null # int
  blacklist: # Iterable[str]. Experiments to blacklist.
    - "" # Accession numbers that exist insdie `data_dir`, but should be excluded from training.

  metadata_ckpt: '/path/to/previous/metadata/directory' # str. Directory from previous run. This ensures training and validation experiments do not change when training is resumed from a checkpoint. Set to null to not use metadata from a previous run.

# Parameters to initialize the trainer
# parameter choices and defaults can be found here: https://lightning.ai/docs/pytorch/stable/common/trainer.html#init
trainer:
  accelerator: 'auto' # str | Accelerator. Choices are ("cpu", "gpu", "tpu", "hpu", "mps", "auto")
  precision: '32-true' # int. Trainer precision.
  devices: 8 # int.
  num_nodes: 4 # int. Number of nodes to use for training.
  max_steps: 100000 # int. Number of steps to use for training.
  check_val_every_n_epoch: 50 # int. Number of epochs between validation set evaluation.
  log_every_n_steps: 1 # int. Number of steps between logging.
  gradient_clip_val: 1 # float
  accumulate_grad_batches: 2 # int (effective batch size is `accumulate_grad_batches` * `batch_size`)
  use_distributed_sampler: false # bool

# Parameters to initialize the logger
# parameter choices and defaults for Wandb logger can be found here: https://lightning.ai/docs/pytorch/stable/extensions/generated/lightning.pytorch.loggers.WandbLogger.html#wandblogger
# and kwargs options found here https://docs.wandb.ai/ref/python/init
logger:
  use_wandb: true # bool. Use W&B to log training metrics and checkpoints.
  name: 'Pre-train ARCH3D' # str. Display name of run for Wandb.
  save_dir: '/path/to/wandb/save/directory' # Path. Path to where Wandb saves data.
  offline: false # bool. Use W&B in offline mode.
  project: 'WandB Project Name' # str. The name of the W&B project.
  log_model: true # Literal["all"] | bool. Log model checkpoints on Wandb. "all" logs checkpoints as they are created, true logs checkpoints at the end of training, and false does not log checkpoints.
